### PR TITLE
Add technical documentation for paid-membership site built using SAWO and Stripe

### LINKED ISSUE #2: Technical guide on How to build a paid membership site with Stripe and SAWO
We are seeking a technical guide on "How to build a paid membership site with Stripe and SAWO". Write according to the template as mentioned [here](https://github.com/Sawo-Community/Sawo-Docs/tree/main/Template-for-Guides). Try to be as creative as possible.

Strictly mention this issue, while submitting a Pull Request related to this issue. You can comment freely under this issue if you have any questions regarding the content. 

If you make a video tutorial walkthrough, make sure to include it in your markdown submission. Give a proper title and description to your PR.

### PR DESCRIPTION
**Pull request by karankartikeya**
Integrated SAWO for authentication and Stripe for payments. This example project covers every aspect of the project and is available with the demo video.

Tech-stacks used:
*  NodeJs
Authentication:
* SAWO:
Payment Portal;
* Stripe 

Short Description of the project:
The project currently runs on localhost due to the Stripe API. The project has a basic UI with a buy membership option which is only available to authenticated users only. After signing in with SAWO, the users can buy membership using Stripe.

Closes #2

### CODE REVIEW

**Comment by SawoCommunity** [comment]
Thanks for the contribution @karankartikeya

**Comment by SawoCommunity** [comment]
@karankartikeya your PR is not showing any changes.

**Comment by karankartikeya** [comment]
but it was showing before, I'll check and revert back accordingly.

**Comment by karankartikeya** [comment]
Please check it now. I have pushed the code again

**Comment by karankartikeya** [comment]
Respected sir/mam,
Why are my commits again and again being removed by the pull bot?
My commits are not visible now.
Is this to be resolved?

My commit a9a1681 has been replaced by the other commit.
Please check it

**Comment by SawoCommunity** [comment]
Hey @karankartikeya not understanding that from our end too! But the documentation looks really fine. Can you tell your discord ID?

**Comment by karankartikeya** [comment]
> Hey @karankartikeya not understanding that from our end too! But the documentation looks really fine. Can you tell your discord ID?



> Hey @karankartikeya not understanding that from our end too! But the documentation looks really fine. Can you tell your discord ID?

It's Karan Kartikeya #2855

**Comment by SawoCommunity** [comment]
@karankartikeya Thanks a lot! Can you change the name of your folder from content to Stripe?

**Comment by karankartikeya** [comment]
> @karankartikeya Thanks a lot! Can you change the name of your folder from content to Stripe?

Please check it, I have changed the folder name to Stripe.

**Comment by SawoCommunity** [comment]
Thanks a lot

**Pull request merged**
