### PR TITLE
Add docs for integration in Gatsby

### LINKED ISSUE #1: Technical guide on How to add Sawo to a Gatsby site
We are seeking a technical guide on "How to add SAWO to a Gatsby site". Write according to the template as mentioned [here](https://github.com/Sawo-Community/Sawo-Docs/tree/main/Template-for-Guides). Try to be as creative as possible.

Strictly mention this issue, while submitting a Pull Request related to this issue. You can comment freely under this issue if you have any questions regarding the content. 

If you make a video tutorial walkthrough, make sure to include it in your markdown submission. Give a proper title and description to your PR.

### PR DESCRIPTION
**Pull request by irsayvid**
This documentation contains brief intro to Gatsby and how one can get started with Gatsby. Later, I've shown how to generate an API key and authenticate using it by installing necessary packages. I've linked a hands on tutorial video and source code for the same.

closes #1

### CODE REVIEW

**Comment by SawoCommunity** [comment]
@irsayvid Please describe the PR briefly. Describe briefly in two or three sentences about the content you have written. Additionally mention if you have created any video tutorial along with the technical documentation.

**Comment by SawoCommunity** [comment]
@irsayvid Please restructure your document according to the template guide found [here](https://github.com/Sawo-Community/Sawo-Docs/tree/main/Template-for-Guides#template-for-making-guides).

**Comment by irsayvid** [comment]
@SawoCommunity Can you please review again and suggest any changes if needed

**Comment by SawoCommunity** [comment]
@irsayvid Thanks for the modification. The changes are on point.

**Comment by SawoCommunity** [comment]
@irsayvid can u please check why the images are not showing in your documentation??

**Comment by irsayvid** [comment]
[image](url)
They are perfectly being shown in my forked repo. Can you cross check once

**Comment by irsayvid** [comment]
They're being displayed in my forked repo. Can you cross check once

**Comment by SawoCommunity** [comment]
@irsayvid it's not showing in the PR preview. Wait! I am checking

**Review by SawoCommunity — APPROVED** [review]

**Comment by SawoCommunity** [comment]
@irsayvid can you give me the sample app repository for the Gatsby integration??

**Comment by irsayvid** [comment]
Sure! This is it: https://github.com/irsayvid/gatsby-sawo

**Pull request merged**
