### PR TITLE
Create Integrating SAWO in Gatsby

### PR DESCRIPTION
**Pull request by amanraj-iit**
In this documentation i have tried to provide step by step process to integrate the SAWO in Gatsby
some topics covers are : how to make API keys, Integration process, About Gatsby ,Features of SAWO,etc
Hope you will love it.

Documentation ,

SAWO Week of Docs

### CODE REVIEW

**Comment by amanraj-iit** [comment]
@SawoCommunity

**Comment by SawoCommunity** [comment]
@amanraj-iit give a proper description in your Pull Request. The doc looks fine. Thanks for the contribution

**Comment by amanraj-iit** [comment]
@SawoCommunity please check

**Comment by SawoCommunity** [comment]
Thanks @amanraj-iit

**Comment by Sayanta66** [comment]
Hey @amanraj-iit can you provide the source code of your sample app integration? And if possible can you provide a video of your Integration??

**Comment by SawoCommunity** [comment]
As you haven't responded, we have closed this PR.

**Comment by amanraj-iit** [comment]
@SawoCommunity 
Project:
https://github.com/amanraj-iit/Hackathon-Project-01.git

Video Link: https://youtu.be/iWDP0txq_X0

**Pull request closed without merging**
