### PR TITLE
Documentations for integrating SAWO in Both - Gatsby and Next.js

### PR DESCRIPTION
**Pull request by shreya-gb**
I have attached the `Documentation.md` file and Image files, in the folder  of `Gatsby` Folder

### CODE REVIEW

**Comment by SawoCommunity** [comment]
@shreya-gb Please give a brief description of your PR. Mention the issue it solves. In the last part of your documentation, give a proper conclusion. And, add a section of "What's next?" according to the template.

**Comment by shreya-gb** [comment]
> @shreya-gb Please give a brief description of your PR. Mention the issue it solves. In the last part of your documentation, give a proper conclusion. And, add a section of "What's next?" according to the template.

Thank you for the feedback. I'll update it ASAP!

**Review by shreya-gb — COMMENTED** [review]
This document includes:
- [x] What is Gatsby? Who uses Gatsby? & How can one get started with Gatsby? 🎯 
- [x] The steps to integrate SAWO API with Gatsby. 🎯 
- [x] Demonstrated authentication using the SAWO API key.  🎯 
- [x] Mentioned & Quoted the essential Packages.  🎯 
- [x] My PR follows the SAWO Documentation Template. 🎯 
- [x] Closes Issue #1

**Comment by shreya-gb** [comment]
@SawoCommunity Please could you review this edited PR? I have worked on all the above feedbacks.

**Comment by SawoCommunity** [comment]
@shreya-gb the changes are perfect. Thanks a lot for your contribution.

**Review by SawoCommunity — CHANGES_REQUESTED** [review]
I have left several suggestions. Please apply them. I have removed some of the errors. If you have any questions, please let me know

**Review by SawoCommunity — APPROVED** [review]

**Pull request merged**
